### ISSUE TITLE
Wissenschaftliches Paper

### ISSUE THREAD

**Issue by chpa0015** [VRLAB-HSKL/AIS21-1#7]

**Comment by paulf98** [comment]
[https://www.overleaf.com/7365224549xjdbpmnxfzqh](https://www.overleaf.com/7365224549xjdbpmnxfzqh)

**Comment by chpa0015** [comment]
- [x] Einleitung

- [ ] Umsetzung
> - [ ]  Probleme

- [ ] Ausblick/Zukunft

- [ ] Quellen 
> - [ ]  Repos verlinken

**Comment by chpa0015** [comment]
- [ ] Bilder einfügen

**Comment by chpa0015** [comment]
- [ ] Ehrenwörtliche Erklärung unterschreiben
